#!/usr/bin/env bash
set -euo pipefail
mkdir -p output
disk_args=()
if [[ -n "${3:-}" ]]; then
  disk_args=(--argstr disk "${3}")
fi
out=$(nix-build default.nix -A buildIso --argstr partition "${1:-default60G}" --argstr cloud "${2:-false}" "${disk_args[@]}")
cp "$out"/iso/* output/
